import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import ProviderAuth from "@/context/ProviderAuth";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

          <ProviderAuth>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

          <Navbar />
          {children}
          <Toaster />
      </body>
      </ProviderAuth>
    </html>
  );
} 
